spring:
  cloud:
    stream:
      bindings:
        emitHealthTips-in-0:
          destination: health.tip
          group: diet
        emitHealthTips-out-0:
          group: diet
        emitRegistration-in-0:
          destination: registered
          group: patients